### ISSUE TITLE
inside_paths should work with relative directories

### ISSUE THREAD

**Issue by jamesmeador** [pitr/angular-rails-templates#100]
We compile our assets on our production machines as part of our deployment for various infrastructure reasons. This causes angular-rails-templates' inside_paths option to cause problems. The digest is generated based on the inside_paths option which includes an absolute path to a directory. Our paths are different in production between machines because we have a container-based deployment system, and container paths contain UUIDs. This results in assets generated on one machine being unavailable on other machines.

Can the inside_paths configuration be modified to work with relative paths instead of Rails.root-oriented absolute paths?

**Comment by redterror** [comment]
Piling on, I am in the same boat.  In my case deploy directories use the capistrano-style timestamped directories, and so they vary slight between hosts since deploys don't happen at the exact same second.

This results in different `Rails.application.config.angular_templates` objects across servers, which means different `hexdigest` results, which means different `Sprockets::Environment.digest` objects, which means different asset digests across a cluster.
