### ISSUE TITLE
How do I access my helpers?

### ISSUE THREAD

**Issue by omenking** [pitr/angular-rails-templates#45]
I'm moving my haml templates from my views to my templates directory. I make use of lots of helpers. How can I get access to my helper methods?

**Comment by poc7667** [comment]
The conclusion is ` 'angular-rails-templates'` won't be able to access Rails helper, right?

**Comment by pitr** [comment]
Correct. `angular-rails-templates` only puts your angular templates into asset pipeline, which does not support helpers. However, [whitehat101's comment](https://github.com/pitr/angular-rails-templates/issues/45#issuecomment-43229086) might help

**Comment by poc7667** [comment]
@pitr  thank you

**Comment by Whyves** [comment]
@poc7667 

I was able to add the Rails helpers when generating the haml file. I explained how to do it on this [thread on StackOverflow](http://stackoverflow.com/questions/22976912/rails-app-to-angular-haml-rails-helpers/27335706#27335706). I did it on version 0.1.3 at the time and has not yet upgraded to 1.0.0 but I assume that it should work nonetheless.

**Comment by vicmaster** [comment]
I know this issue was closed, but If you are migrating to rails 5.x and have angular-rails-templates gem, the workaround to include view helpers in haml templates does not work anymore, instead of `Tilt.register CustomHamlEngine::HamlTemplate, '.haml'` use: `Tilt.register CustomHamlEngine::HamlTemplate, 'haml'` using the @Whyves approach.
