### ISSUE TITLE
using blocks in a template?

### ISSUE THREAD

**Issue by brightbits** [pitr/angular-rails-templates#72]
I'm getting a syntax error with this like:

```html
<div class="row">
    <%= form_for (:something) do |f| %> <!-- this one -->
      hi
    <% end %>
  </div>
```

The stack trace looks like:

```
app/assets/templates/games/new/main.html.erb:5: syntax error, unexpected ')'
... form_for (:something) do |f| ).to_s); _erbout.concat "\n"
...                               ^
app/assets/templates/games/new/main.html.erb:13: syntax error, unexpected keyword_ensure, expecting ')'
app/assets/templates/games/new/main.html.erb:15: syntax error, unexpected keyword_end, expecting ')'
```

Any idea why this basic thing wouldn't be working through templates when they use the same templating engine as normally used?

**Comment by sansjunk** [comment]
@brightbits I am having the exact same problem, mind sharing what you did to solve it?

**Comment by pitr** [comment]
I am guessing a space before opening bracket in `form_for (:something)`

**Comment by mfkp** [comment]
@sansjunk did you get it working? I am running into this problem now, here is the code that is failing (works in a regular erb template):

```ruby
<%= link_to 'zombo.com' do %>
    <%= image_tag 'my-image.png' %>
<% end %>
```

**Comment by sansjunk** [comment]
@mfkp no, unfortunately not. I just circumvented the problem by not using form_for :)

**Comment by mfkp** [comment]
Thanks @sansjunk.

@pitr - maybe we should re-open this issue as it still seems to be a problem.

**Comment by qbabin** [comment]
@pitr pls respond

**Comment by qbabin** [comment]
@sansjunk what did you do to not use the form_for? i'm in the same exact boat

**Comment by mfkp** [comment]
@pitr pls

@qbabin I assume he just wrote a standard form tag around it, that's why I did for my <a> tag (not ideal, but it works).

**Comment by pitr** [comment]
@mfkp @qbabin what does your error say?

**Comment by mfkp** [comment]
```
SyntaxError - syntax error, unexpected ')'
        '; _erbout << ( link_to 'zombo.com' do ).to_s; _erbout << '
```

with this code:

```erb
<%= link_to 'zombo.com' do %>
  <%= image_tag 'my-image.png' %>
<% end %>
```

**Comment by qbabin** [comment]
^ anytime I have a do block with a form_for I get the same error

**Comment by pitr** [comment]
Ah. unfortunately this is a limitation of this gem. Angular templates are processed during Rails asset compilation. You have no views, controllers, etc. Some of view helper functions kinda work (like `link_to name, url`) simply because they don't depend on anything. However, it breaks down very fast. `form_for` is a bad idea if you care about CSRF protection. For rendering you need proper view renderer that knows where to look for partials. I tried
```erb
<% link_to 'zombo.com' do %>
  <%= image_tag 'my-image.png' %>
<% end %>
```

Which errored out due to `undefined method `output_buffer=' for #<#<Class:0x007fd991433d08>:0x007fd99164a6f0>` This is again, due to absence of actual "view"
