### ISSUE TITLE
Templates do not work with `initialize_on_precompile=false`

### ISSUE THREAD

**Issue by squirly** [pitr/angular-rails-templates#84]
When `initialize_on_precompile=false` the `angular-rails-templates` initializer does not run.

It needs to be in the assets initializer group to fix this.

**Comment by squirly** [comment]
Will have a pull request in a few minutes.

**Comment by Asciant** [comment]
I am not entirely sure why, although this update completely broke my application on rails 4.2.0.

When I reverted back to 0.1.3 everything went back to normal. 

I will try and establish where exactly the problem came up, to determine if it was an error in my application internally, or something directly related to this pull request.
